# -*- coding: utf-8 -*-
"""Data Integration Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbLfWlAve0cAQFdemUj7-885TXEO3weP
"""

import pandas as pd

cases_df = pd.read_csv('cases.csv')
deaths_df = pd.read_csv('deaths.csv')
census_df = pd.read_csv('census.csv')

cases_df = cases_df[['County Name', 'State', '2023-07-23']]
deaths_df = deaths_df[['County Name', 'State', '2023-07-23']]
census_df = census_df[['County', 'State', 'TotalPop', 'IncomePerCap', 'Poverty', 'Unemployment']]

print(cases_df.columns.values.tolist())
print(deaths_df.columns.values.tolist())
print(census_df.columns.values.tolist())

cases_df['County Name'] = cases_df['County Name'].str.strip()
deaths_df['County Name'] = deaths_df['County Name'].str.strip()

print(len(cases_df[cases_df['County Name'] == "Washington County"]))
print(len(deaths_df[deaths_df['County Name'] == "Washington County"]))

print(len(cases_df))
print(len(deaths_df))
cases_df = cases_df[cases_df['County Name'] != "Statewide Unallocated"]
deaths_df = deaths_df[deaths_df['County Name'] != "Statewide Unallocated"]
print(len(cases_df))
print(len(deaths_df))

us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
}

# invert the dictionary
abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

cases_df['State'] = cases_df['State'].map(abbrev_to_us_state)
deaths_df['State'] = deaths_df['State'].map(abbrev_to_us_state)
cases_df.head()

cases_df['Key'] = cases_df['County Name'] + ' ' + cases_df['State']
deaths_df['Key'] = deaths_df['County Name'] + ' ' + deaths_df['State']
census_df['Key'] = census_df['County'] + ' ' + census_df['State']
cases_df.set_index('Key')
deaths_df.set_index('Key')
census_df.set_index('Key')
census_df.head()

cases_df = cases_df.rename(columns={'2023-07-23': 'Cases'})
deaths_df = deaths_df.rename(columns={'2023-07-23': 'Deaths'})

print(cases_df.columns.values.tolist())
print(deaths_df.columns.values.tolist())

join_df = pd.merge(cases_df, deaths_df)
join_df = pd.merge(census_df, join_df)
join_df['CasesPerCap'] = join_df['Cases'] / join_df['TotalPop']
join_df['DeathsPerCap'] = join_df['Deaths'] / join_df['TotalPop']
print(len(join_df))

correlation_matrix = join_df.corr(numeric_only=True)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)

plt.title('Correlation Matrix Heatmap')
plt.show()